### ISSUE TITLE
ng serve error

### ISSUE THREAD

**Issue by wfyuen** [curtis-noel/angularui#1]
After checking out either branch and running "npm install" and "npm start" (the 'ng serve' step), I got this error running from my Arch linux box:

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/home/wing/angularui/node_modules/angular-cli/tasks/serve.js:22:61)
    at /home/wing/angularui/node_modules/angular-cli/commands/serve.run.js:22:22
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo2@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo2@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wing/.npm/_logs/2018-08-20T23_46_28_214Z-debug.log

wing@guru-manjaro ~/angularui> node --version
v10.9.0
wing@guru-manjaro ~/angularui> npm --version
6.4.0

How do I set the "config" property?

**Comment by zobairsaleem** [comment]
This usually happens if there is a version mismatch. The app is running on Angular 6, which looks for "angular.json" file for configurations, where as prior versions look for an "angular-cli.json" file. I suspect your angular cli version (if it was already installed before npm install) may be a lower version that is looking for "angular-cli.json" instead of "angular.json". 

Can you run "ng --version" and check your @angular/cli version and make sure its 6.x.x?
If not, try running "npm install -g @angular/cli" to update to latest version. 

Let me know if this helps.

**Comment by wfyuen** [comment]
Thanks, I am pretty you nailed it. The package.json has angular-cli locked
at v2 I recall. Npm install threw up a warning to upgrade.

Wing.

**Comment by wfyuen** [comment]
Problem resolved after upgrading to Node v8.11 LTS.
